### ISSUE TITLE
Reach out

### ISSUE THREAD

**Issue by AndrewsPanda** [FuseFairy/FuseFairy#1]
Hi FuseFairy! I've enjoyed your work on your EdgeGPT bot and you seem fairly active. I was wondering if you have much experience with py? The reason being is because I have some projects that needs minor adjustments etc and I am looking to pay someone for this work.

If you're interested in talking more you can add me on discord:  PandasaurusRex#7608

Have a great day!

**Comment by FuseFairy** [comment]
Ok, I have sent a friend request.name: zhuang#5431 從 Windows 的郵件傳送 寄件者: AndrewsPanda傳送時間: 2023年5月31日 上午 10:13收件者: FuseFairy/FuseFairy副本: Subscribed主旨: [FuseFairy/FuseFairy] Reach out (Issue #1) Hi FuseFairy! I've enjoyed your work on your EdgeGPT bot and you seem fairly active. I was wondering if you have much experience with py? The reason being is because I have some projects that needs minor adjustments etc and I am looking to pay someone for this work.If you're interested in talking more you can add me on discord: PandasaurusRex#7608Have a great day!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
